version: '3.1'

services:

  db:
    image: postgres
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    # app uses port 8080 for now, map to 8081
    ports:
      - 8081:8080