package com.bastronaut.bigspender.utils;

import com.bastronaut.bigspender.config.SecurityUtil;
import com.bastronaut.bigspender.models.Label;
import com.bastronaut.bigspender.models.Transaction;
import com.bastronaut.bigspender.models.TransactionImport;
import com.bastronaut.bigspender.models.User;
import lombok.Getter;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

import static com.bastronaut.bigspender.enums.TransactionCode.BA;
import static com.bastronaut.bigspender.enums.TransactionCode.GT;
import static com.bastronaut.bigspender.enums.TransactionMutationType.BETAALAUTOMAAT;
import static com.bastronaut.bigspender.enums.TransactionMutationType.DIVERSEN;
import static com.bastronaut.bigspender.enums.TransactionMutationType.ONLINEBANKIEREN;
import static com.bastronaut.bigspender.enums.TransactionType.AF;
import static com.bastronaut.bigspender.enums.TransactionType.BIJ;


/**
 * Class containing sample data for unit tests. Has some non-static fields as to avoid problems where JPA has set
 * autogenerated ID fields or other fields after persistence of entities, but this is not cleaned up as these entities
 * are reset in the db. Additionally, jpa does not do well with persisting static entities
 */
public class SampleData {

    // Setup two sample users
    public static final String USERNAMEONE = "test@email.com";
    public static final String USERNAMETWO = "testTwo@email.com";
    public static final String TEST_PASSWORD = "testpassword";
    public static final String ENCODED_TEST_PW =  SecurityUtil.encode(TEST_PASSWORD);
    @Getter
    private final User testUserOne = new User(USERNAMEONE, ENCODED_TEST_PW);
    @Getter
    private final User testUserTwo = new User(USERNAMETWO,  ENCODED_TEST_PW);

    public static final String USERNAMEPW_USERONE = USERNAMEONE + ":" + TEST_PASSWORD;
    public static final String USERNAMEPW_USERTWO = USERNAMETWO + ":" + TEST_PASSWORD;
    public static final String USERNAMEPW_USERONE_FAKE = USERNAMEONE + ":" + "fakepw";

    final public static String HEADER_ENCODED_USERONE = "Basic " + (Base64.getEncoder().encodeToString(USERNAMEPW_USERONE.getBytes()));
    final public static String HEADER_ENCODED_USERTWO = "Basic " + (Base64.getEncoder().encodeToString(USERNAMEPW_USERTWO.getBytes()));
    final public static String HEADER_ENCODED_NONEXISTINGUSER = "Basic " + (Base64.getEncoder().encodeToString("nonexisting@email.com:fakepw".getBytes()));
    final public static String HEADER_ENCODED_USERONEWRONGPW = "Basic " + (Base64.getEncoder().encodeToString(USERNAMEPW_USERONE_FAKE.getBytes()));

    public static final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");

    /**
     * Sample transactions.csv map to the following t1-t7:
     *
     * t1 "20190401","AH to go 5869 DenHaa","NL41INGB0006212385","","BA","Af","1,80","Betaalautomaat","Pasvolgnr: 008 01-04-2019 22:39 Valutadatum: 02-04-2019"
     * t2 "20190402","AH to go 5869 DenHaa","NL41INGB0006451386","","BA","Bij","11,80","Betaalautomaat","Pasvolgnr: 008 01-04-2019 02:39 Valutadatum: 02-04-2019"
     * t3 "20190403","AH to go","NL20INGB0001234567","NL20INGB0007654321","BA","Af","19,80","Online bankieren","Pasvolgnr: 008 01-04-2019 14:15 Valutadatum: 02-04-2019"
     * invalid "20190407","Invalid row missing column","NL20INGB0004567891","NL20INGB0001987654","BA","Bij","19,80","Online bankieren"
     * t4 "20190404","to go","NL20INGB0001234567","NL20INGB0007654321","BA","Af","51,21","Online bankieren","Pasvolgnr: 008 01-04-2019 16:15 Valutadatum: 02-04-2019"
     * t5 "20190405","AH to go Den","NL20INGB0002345678","NL20INGB0007654321","GT","Af","141,20","Diversen","Pasvolgnr: 008 01-04-2019 23:01 Valutadatum: 02-04-2019"
     * t6 "20190406","AH to go go","NL20INGB0003456789","NL20INGB0007654321","GT","Af","9999,99","Online bankieren","Pasvolgnr: 008 01-04-2019 Valutadatum: 02-04-2019"
     * t7 "20190407","test to go go yes","NL20INGB0004567891","NL20INGB0001987654","BA","Bij","19,80","Diversen","Pasvolgnr: 008 01-04-2019 07:25 Valutadatum: 02-04-2019"
     */
    public final Transaction t1 = new Transaction(LocalDate.of(2019, 04, 01),
            LocalTime.of(22,39), "AH to go 5869 DenHaa", "NL41INGB0006212385",
            null, GT, AF, 180, BETAALAUTOMAAT,
            "Pasvolgnr: 008 01-04-2019 22:39 Valutadatum: 02-04-2019", testUserOne);
    public final Transaction t2 = new Transaction(LocalDate.of(2019, 04, 02),
            LocalTime.of(02,39), "AH to go 5869 DenHaa", "NL41INGB0006451386",
            null, BA, BIJ, 1180, BETAALAUTOMAAT,
            "Pasvolgnr: 008 01-04-2019 02:39 Valutadatum: 02-04-2019", testUserOne);

    public final Transaction t3 = new Transaction(LocalDate.of(2019, 04, 03),
            LocalTime.of(14,15), "AH to go", "NL20INGB0001234567",
            "NL20INGB0007654321", BA, AF, 1980, ONLINEBANKIEREN,
            "Pasvolgnr: 008 01-04-2019 14:15 Valutadatum: 02-04-2019", testUserOne);

    public final Transaction t4 = new Transaction(LocalDate.of(2019, 04, 04),
            LocalTime.of(16,15), "to go", "NL20INGB0001234567",
            "NL20INGB0007654321", BA, AF, 5121, ONLINEBANKIEREN,
            "Pasvolgnr: 008 01-04-2019 16:15 Valutadatum: 02-04-2019", testUserOne);

    public final Transaction t5 = new Transaction(LocalDate.of(2019, 04, 05),
            LocalTime.of(23,01), "AH to go Den", "NL20INGB0002345678",
            "NL20INGB0007654321", GT, BIJ, 14120, DIVERSEN,
            "Pasvolgnr: 008 01-04-2019 23:01 Valutadatum: 02-04-2019", testUserOne);

    public final Transaction t6 = new Transaction(LocalDate.of(2019, 04, 06),
            null, "AH to go go", "NL20INGB0003456789",
            "NL20INGB0007654321", GT, AF, 999999, ONLINEBANKIEREN,
            "Pasvolgnr: 008 01-04-2019 Valutadatum: 02-04-2019", testUserOne);

    public final Transaction t7 = new Transaction(LocalDate.of(2019, 04, 07),
            LocalTime.of(07,25), "test to go go yes", "NL20INGB0004567891",
            "NL20INGB0001987654", BA, BIJ, 1980, DIVERSEN,
            "Pasvolgnr: 008 01-04-2019 07:25 Valutadatum: 02-04-2019", testUserOne);


    private final List<Transaction> transactions = new ArrayList<>();

    public List<Transaction> getTransactions() {
        if (transactions.isEmpty()) {
            transactions.add(t1);
            transactions.add(t2);
            transactions.add(t3);
            transactions.add(t4);
            transactions.add(t5);
            transactions.add(t6);
            transactions.add(t7);
        }
        return transactions;
    }

    @Getter
    private final TransactionImport sampleTransactionImport = new TransactionImport(getTransactions(), testUserOne);

    @Getter
    private final Transaction t1TESTUSERTWO = new Transaction(LocalDate.of(2019, 04, 01),
            LocalTime.of(22,39), "AH to go 5869 DenHaa", "NL41INGB0006212385",
            null, GT, AF, 180, BETAALAUTOMAAT,
            "Pasvolgnr: 008 01-04-2019 22:39 Valutadatum: 02-04-2019", testUserTwo);

    @Getter
    Label labelOne = new Label("groceries", testUserOne, "#111");
    @Getter
    Label labelTwo = new Label("clothing", testUserOne, "#112");
    @Getter
    Label labelThree = new Label("snacks", testUserOne, "#113");

}
